#swagger : "2.0"
openapi: 3.0.3
info:
  title : Project SWAGGER API
  description : made by me
  version : 1.0
  contact:
    email: odubanjotunde@gmail.com
  license :
    name: Apache 2.0
    url: "http://apache.org/"
  servers:
    -url: "http://localhost:5000/"
    description: This is my local server
    -url: "http://tundeOdu.com"
    description: This is my company server

schemes: [http , https]

paths:
  /api/goal/{userId}:
    get:
      summary: Object of Goal
      description: Returning a single goal
      parameters:
      - name: userId
        in: path
        required : true
        schema:
          type:
            id: string
      responses:
        200:
          description: success

    put:
      description: This endpoint is used to update data
      operationId: UpdateGoal     
      parameters:
        - name: userId
          in: path
          description: id to be updated
          required :  true
            schema :
              type : object
      requestBody:
        description: Update an exiting Goal
        content:
          application/json:  
            schema:             
              type: object
              properties:                  
                name:
                  type: string
                age:
                  type: integer        
      responses:
        200:
          description: ok
              
    delete:
      description: delete Goal from here 
      parameters:
        - name: userId
          in: path
          description: id to be updated
          required :  true
            schema :
              type : object
      responses:
        200:
          description : Success

          
  /api/goal:
    get:
      description: 
      summary: Returns arrays of Object
      responses:
        200: 
          description: sucess
          schema: 
            type: array
            items:
              type: object
              properties:
                name: 
                  type: string
                age:
                  type: integer
                id:
                  type: string

# no need to specify /api/post because the get above and this post are calling the same endpoints  
    post:
      description: Posting Goals
      summary: This will add a goal
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
      - in: body
        name: goalBody
        schema:
          type: object
          properties:          
            name:
              type: string
            age:
              type: integer 
      responses:
        201:
          description : Ok

  
   